### ISSUE TITLE
Problems with zsh?

### ISSUE THREAD

**Issue by ngryman** [shannonmoeller/up#1]
Hey,

Me again, it seems that there are some problems with `zsh`:

![image](https://cloud.githubusercontent.com/assets/892048/13333993/f069970a-dc09-11e5-9dcf-3ac6f0a73501.png)

Do you have an idea?

**Comment by shannonmoeller** [comment]
I'll take a look. `bash` and `zsh` handle completion differently so I'm not surprised.

**Comment by ngryman** [comment]
Here is an example from `bd`: https://github.com/vigneshwaranr/bd/blob/master/bash_completion.d/bd.
They are bundling it separately, which I find kind of lame.

To quickfix this, you could simply detect that `complete` is available or that the user is using `bash` and enable it if so, else disable it. I'm not a `shell` specialist so I don't know if it's simple to do.
Then you could add `zsh` auto-complete I guess :)

**Comment by shannonmoeller** [comment]
I've got experimental zsh support in place on the `develop` branch. Mind giving it a whirl?

**Comment by shannonmoeller** [comment]
The error was due to zsh arrays being 1-base while bash arrays are 0-base, so I had to implement a lookup method. Got completion (mostly) working by using the magic `if` statement at the bottom of this example: 

https://github.com/nategood/commando/issues/24#issuecomment-38357137

**Comment by shannonmoeller** [comment]
Been using it for a day and all seems well.
