### ISSUE TITLE
Add it to awesome-shell

### ISSUE THREAD

**Issue by ngryman** [shannonmoeller/up#2]
You should make it work with `zsh` with an install procedure and add it to: https://github.com/alebcay/awesome-shell. That's where I found `bd`.

**Comment by shannonmoeller** [comment]
Sounds good. Thanks! Marketing my stuff has never been a strong suit.

**Comment by ngryman** [comment]
I know right! I'm still learning too :)

**Comment by shannonmoeller** [comment]
https://github.com/alebcay/awesome-shell/pull/142
