### ISSUE TITLE
Add install procedure

### ISSUE THREAD

**Issue by ngryman** [shannonmoeller/up#3]
`curl -o /usr/local/bin/up https://raw.githubusercontent.com/shannonmoeller/up/master/up.sh && chmod+x /usr/local/bin/up`

**Comment by shannonmoeller** [comment]
Thanks for the sample install snippet! Because of the completion stuff, this file should be `source`ed, not executed directly. I'm looking into best practices for shipping this sort of thing.

**Comment by shannonmoeller** [comment]
Added to develop branch.
