### ISSUE TITLE
suggestion on speed

### ISSUE THREAD

**Issue by sarcastyx** [shannonmoeller/up#5]
Hi there, this is not really an issue but more of enhancement suggestion.
First off love the script, had something similar but which would only jump up a number of directories when called like "up 3". Did not have tab-completion functionality at all.

Back on topic, I've noticed when I try and use "up" to jump a number of directories it takes a long time to process. I looked at your script and saw that if you moved the code for lines 65 to 71 before line 57, where it checks for the dir name. It actually runs a lot faster for jumping up by the folder count and it runs about the same when searching for the dirname by tab completion.

**Comment by shannonmoeller** [comment]
Thanks! I'll play around with that.

**Comment by shannonmoeller** [comment]
I appreciate the suggestion, but I think I'm going to leave as-is. People may be relying on matching directory names that start with numbers and I don't want to break that.
