### ISSUE TITLE
Up by "level" or "name" breaks when there is a space in the path

### ISSUE THREAD

**Issue by Asheq** [shannonmoeller/up#7]
Environment Info: I'm on BASH_VERSION: 4.4.19(1)-release

`up 4`
`up <partial-name>`

These don't work if there is a space anywhere in the path.

Spaces occasionally show up in the file system I'm working in, so I hope this is something you can fix. Thanks for this awesome shell script!

**Comment by imambungo** [comment]
Actually, it works. You need to add an escape character `\` before the space.  
If the partial-name is `dir4 new`, then you type `up dir4\ new`.

However, the tab completion doesn't work for every partial-name containing a space.

**Comment by Asheq** [comment]
Does not work with spaces:
![spaces](https://user-images.githubusercontent.com/4657140/61904921-b7ba7880-aedc-11e9-9ee6-b7f3400bc271.gif)

Works with out spaces:
![no-spaces](https://user-images.githubusercontent.com/4657140/61904954-c739c180-aedc-11e9-8f3b-251800f582f3.gif)

**Comment by imambungo** [comment]
Oh, sorry. You're right, it works on zsh but when I tried it on bash, it doesn't work.

**Comment by shannonmoeller** [comment]
PR #8 didn't fully resolve this issue. Reopening.
